import type { ComponentType } from "react";

import { AlarmsScreen, EventsScreen, HistoryScreen, OperationCenter, ReportsScreen, SitesScreen, TrendsScreen } from "./operations";
import { MapScreen } from "./MapScreen";
import {
  AgendaScreen,
  BatteriesScreen,
  EnergyGens,
  EnergyLoad,
  EnergyParallel,
  EnergyRede,
  EnergyTransfer,
  FuelScreen,
  HourmetersScreen,
  MaintenanceScreen,
} from "./energy-maint";
import {
  CommunicationScreen,
  ConnectivityScreen,
  ControllersScreen,
  EscalationScreen,
  ExerciseScreen,
  GatewaysScreen,
  ModemsScreen,
  NotificationsScreen,
  RulesScreen,
  SchedulesScreen,
} from "./equip-auto";
import {
  BackupsScreen,
  ChannelsScreen,
  DiagnosticScreen,
  LabScreen,
  LibControllersScreen,
  ManufacturersScreen,
  PacksScreen,
  ProtocolsScreen,
  RapidScadaScreen,
  SettingsScreen,
  TagsScreen,
  TemplatesScreen,
  VersionScreen,
  HealthScreen,
} from "./scada-lib";
import {
  ApiScreen,
  ClientsScreen,
  EmailScreen,
  ErpScreen,
  UnitsScreen,
  WebhooksScreen,
  WhatsAppScreen,
} from "./mgmt";
import { AuditScreen, RolesScreen, UsersScreen } from "./security";

export const screens: Record<string, ComponentType> = {
  "central-de-operacao": OperationCenter,
  sites: SitesScreen,
  mapa: MapScreen,
  alarmes: AlarmsScreen,
  eventos: EventsScreen,
  tendencias: TrendsScreen,
  historico: HistoryScreen,
  relatorios: ReportsScreen,
  "energia-rede": EnergyRede,
  "energia-geradores": EnergyGens,
  "energia-carga": EnergyLoad,
  "energia-transferencia": EnergyTransfer,
  "energia-paralelismo": EnergyParallel,
  manutencao: MaintenanceScreen,
  combustivel: FuelScreen,
  baterias: BatteriesScreen,
  horimetros: HourmetersScreen,
  agenda: AgendaScreen,
  controladoras: ControllersScreen,
  modems: ModemsScreen,
  gateways: GatewaysScreen,
  conectividade: ConnectivityScreen,
  comunicacao: CommunicationScreen,
  regras: RulesScreen,
  "exercicio-automatico": ExerciseScreen,
  agendamentos: SchedulesScreen,
  notificacoes: NotificationsScreen,
  escalonamento: EscalationScreen,
  canais: ChannelsScreen,
  tags: TagsScreen,
  templates: TemplatesScreen,
  "rapid-scada": RapidScadaScreen,
  diagnostico: DiagnosticScreen,
  fabricantes: ManufacturersScreen,
  "lib-controladoras": LibControllersScreen,
  protocolos: ProtocolsScreen,
  "controller-packs": PacksScreen,
  laboratorio: LabScreen,
  clientes: ClientsScreen,
  unidades: UnitsScreen,
  usuarios: UsersScreen,
  perfis: RolesScreen,
  auditoria: AuditScreen,
  api: ApiScreen,
  webhooks: WebhooksScreen,
  email: EmailScreen,
  whatsapp: WhatsAppScreen,
  "erp-bms": ErpScreen,
  configuracoes: SettingsScreen,
  backups: BackupsScreen,
  saude: HealthScreen,
  versao: VersionScreen,
};
